### ISSUE TITLE
LoGiC.NET v2 module loading error

### ISSUE THREAD

**Issue by kaeso** [AnErrupTion/LoGiC.NET#12]
Hi. After compilation trying to run:

```
[Loading module]
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Program.<Main>$(String[] args) in C:\Users\admin\Desktop\LoGiC.NET.v2\Program.cs:line 4
```
UPD.
Solved (forgot path). But i can't find output file. 
How to use? Thanks.

**Comment by AnErrupTion** [comment]
It's not done yet, I only just started it :D

**Comment by AnErrupTion** [comment]
You can now add an output path in the arguments when launching the obfuscator.
