### ISSUE TITLE
string decryption

### ISSUE THREAD

**Issue by iphqne** [AnErrupTion/LoGiC.NET#3]
![u2Oqibe78U1](https://user-images.githubusercontent.com/45533114/93957863-1384c980-fd4d-11ea-8cd1-8dd472c3f7cc.gif)

**Comment by AnErrupTion** [comment]
LoGiC.NET isn't meant to be a serious obfuscator, but more for learning purposes. Still, you did dedicate a few minutes of your life to do that.
