### ISSUE TITLE
Error running obfuscator after building from source

### ISSUE THREAD

**Issue by Simon-Davies** [AnErrupTion/LoGiC.NET#5]
See the attached image showing the error.

![IMG_20210717_120110](https://user-images.githubusercontent.com/713455/126045713-2a61aff3-a3af-4a7c-8db9-45ccc4205d3f.jpg)

**Comment by AnErrupTion** [comment]
Sorry for the (very) late response @Simon-Davies! Could you send the assembly you're trying to obfuscate so that I can fix the problem?

**Comment by Simon-Davies** [comment]
[Rubeus.zip](https://github.com/AnErrupTion/LoGiC.NET/files/6987792/Rubeus.zip)

I have added the Rubeus binary to a zip file so it would allow me to upload it. The password for the zip file is: Rubeus

**Comment by AnErrupTion** [comment]
It seems to be obfuscating fine on my current changes (though it doesn't execute, I'll check why)

**Comment by AnErrupTion** [comment]
@Simon-Davies It seems to be fixed with the latest git changes, can you try on your machine please?

**Comment by Simon-Davies** [comment]
I confirm it is now working. Thank you.
