### ISSUE TITLE
Protected files are massive

### ISSUE THREAD

**Issue by Simon-Davies** [AnErrupTion/LoGiC.NET#7]
After the recent changes protected files are massive. A 7kB file after protection is over 2MB.

**Comment by AnErrupTion** [comment]
I'm already aware of that, and the solution would be to remove the junk defs or to make less of them. I'll find a way to balance it in the future, for the moment you could edit the obfuscator to turn down the junk defs a bit.

**Comment by Simon-Davies** [comment]
I fixed the problem by removing this code:

```
            // Add junk types
            for (int i = 0; i < MemberRenamer.StringLength(); i++)
            {
                TypeDef type = new TypeDefUser(String(MemberRenamer.StringLength())) { Namespace = string.Empty };
                Program.Module.Types.Add(type);

                Amount++;
            }
```
