### ISSUE TITLE
AV Detections caused by obfuscation

### ISSUE THREAD

**Issue by Simon-Davies** [AnErrupTion/LoGiC.NET#8]
The obfuscation causes these AV detections:

![image](https://user-images.githubusercontent.com/713455/130154773-cbe977ec-a610-4279-8aa7-8c2c0aa44d38.png)

**Comment by AnErrupTion** [comment]
Those are heuristic results, which mean that they use "logic" to determine if a file looks suspicious or not (to make it simple). Unfortunately we can't really avoid that, obfuscators will _always_ generate false positives in one or more AVs, sadly.

**Comment by Simon-Davies** [comment]
It's the addition of all the junk data that likely causes the detections. I have a lot of experience with manually bypassing AV.

**Comment by Simon-Davies** [comment]
I have removed both AV detections by commenting out one of the Protections :)

```
            Protection[] protections = new Protection[]
            {
                new Renamer(),
                new AntiTamper(),
                new JunkDefs(),
                new StringEncryption(),
                new AntiDe4dot(),
                new ControlFlow(),
                //new IntEncoding(),
                new ProxyAdder(),
                new InvalidMetadata()
            };
```
